[package]
name = "mmx-keygen"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.11.0"
bip39 = "2.1.0"
hex = "0.4.3"
hmac = "0.12.1"
inquire = "0.7.5"
rand_core = { version = "0.6.4", features = ["getrandom"] }
secp256k1 = "0.30.0"
sha2 = "0.10.8"
